/*
 * login.java
 *
 * Created on __DATE__, __TIME__
 */

package gui.dao;

import bin.test;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class login extends javax.swing.JFrame {

	/** Creates new form login */
	public login() {
		initComponents();
		setLocationRelativeTo(null);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(test.IMGPATH+"texs.jpg"));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u5728\u5de5\u5927\u7ba1\u7406\u7cfb\u7edf\u767b\u5f55");

		jLabel1.setText("\u5e10\u53f7\uff1a");

		jLabel2.setText("\u5bc6\u7801\uff1a");

		jButton1.setIcon(new javax.swing.ImageIcon(
				"D:\\HintSoft\\Hint-W7\\Desktop\\200\\200\\�ز�\\��¼.png")); // NOI18N
		jButton1.setText("\u767b\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(
				"D:\\HintSoft\\Hint-W7\\Desktop\\200\\200\\�ز�\\����.png")); // NOI18N
		jButton2.setText("\u91cd\u7f6e");

		jLabel3.setIcon(new javax.swing.ImageIcon(
				"D:\\HintSoft\\Hint-W7\\Desktop\\200\\200\\�ز�\\QQͼƬ20170320232814.jpg")); // NOI18N

		jLabel4.setFont(new java.awt.Font("����", 1, 18));
		jLabel4.setForeground(new java.awt.Color(255, 102, 102));
		jLabel4.setText("\u5b66\u5728\u5de5\u5927\u7ba1\u7406\u7cfb\u7edfV1.0");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(25, 25, 25)
						.add(jLabel3)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												81, Short.MAX_VALUE)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING)
												.add(layout
														.createSequentialGroup()
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(jLabel1)
																.add(jLabel2))
														.add(27, 27, 27)
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.TRAILING,
																		false)
																.add(org.jdesktop.layout.GroupLayout.LEADING,
																		jTextField2)
																.add(org.jdesktop.layout.GroupLayout.LEADING,
																		jTextField1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		145,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
												.add(layout
														.createSequentialGroup()
														.add(jButton1)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jButton2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																93,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
								.add(layout
										.createSequentialGroup()
										.add(97, 97, 97)
										.add(jLabel4,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)))
						.add(54, 54, 54)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(jLabel3,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								384,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.add(103, 103, 103)
								.add(jLabel4,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										52,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED,
										105, Short.MAX_VALUE)
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel1)
										.add(jTextField1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel2)
										.add(jTextField2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING,
												false)
										.add(jButton2,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE).add(jButton1))
								.add(49, 49, 49)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//���е�¼
		Index index = new Index();
		index.show();
		this.hide();
	}

	/**
	 * @param args the command line arguments
	 */
	/*public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new login().setVisible(true);
			}
		});
	}*/

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}