/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;

/**
 *
 * @author xy16
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Launcher = new javax.swing.JDialog();
        usernameInputer = new javax.swing.JComboBox<>();
        launchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rememberUser = new javax.swing.JCheckBox();
        rememberKey = new javax.swing.JCheckBox();
        autoLaunch = new javax.swing.JCheckBox();
        passwordInputer = new javax.swing.JPasswordField();
        lauch = new javax.swing.JPanel();
        lauchButton = new javax.swing.JButton();
        lauchLabel = new javax.swing.JLabel();
        windowButton = new javax.swing.JPanel();
        settingButton = new javax.swing.JButton();
        announcementPanel = new javax.swing.JPanel();
        announcementShow = new javax.swing.JScrollPane();
        announcementText = new javax.swing.JTextPane();
        announcementSendButton = new javax.swing.JButton();
        announcementEditPanel = new javax.swing.JScrollPane();
        announcementEdit = new javax.swing.JTextPane();
        buttonArea = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        title = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        midArea = new javax.swing.JSplitPane();
        rightArea = new javax.swing.JTabbedPane();
        centerArea = new javax.swing.JPanel();
        inputScrollPanel = new javax.swing.JScrollPane();
        inputTextPanel = new javax.swing.JTextPane();
        messageButtonPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        messageSendButton = new javax.swing.JButton();
        exchangeButton = new javax.swing.JButton();
        showScrollPanel = new javax.swing.JScrollPane();
        showTextPanel = new javax.swing.JTextPane();
        drawPanel = new javax.swing.JPanel();
        roomScrollPanel = new javax.swing.JScrollPane();
        roomList = new javax.swing.JList<>();
        painterToolPanel = new javax.swing.JToolBar();
        jButton10 = new javax.swing.JButton();
        leftArea = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        fileMenu = new javax.swing.JMenu();

        Launcher.setAlwaysOnTop(true);
        Launcher.setBackground(new java.awt.Color(204, 204, 255));
        Launcher.setResizable(false);

        usernameInputer.setEditable(true);
        usernameInputer.setModel(new javax.swing.DefaultComboBoxModel<>());
        usernameInputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputerActionPerformed(evt);
            }
        });

        launchButton.setText("登录");
        launchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("文泉驿等宽微米黑", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("登录学在工大");

        rememberUser.setText("记住用户名");
        rememberUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberUserActionPerformed(evt);
            }
        });

        rememberKey.setText("记住密码");

        autoLaunch.setText("自动登录");

        passwordInputer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout LauncherLayout = new javax.swing.GroupLayout(Launcher.getContentPane());
        Launcher.getContentPane().setLayout(LauncherLayout);
        LauncherLayout.setHorizontalGroup(
            LauncherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LauncherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LauncherLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(LauncherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordInputer)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LauncherLayout.createSequentialGroup()
                        .addComponent(rememberUser, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rememberKey, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(autoLaunch))
                    .addComponent(usernameInputer, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LauncherLayout.setVerticalGroup(
            LauncherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LauncherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(LauncherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameInputer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(launchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordInputer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(LauncherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rememberKey)
                    .addComponent(rememberUser)
                    .addComponent(autoLaunch))
                .addGap(54, 54, 54))
        );

        setBackground(new java.awt.Color(204, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N

        lauch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lauchMouseDragged(evt);
            }
        });
        lauch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lauchMousePressed(evt);
            }
        });

        lauchButton.setText("登录");
        lauchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lauchButtonMouseClicked(evt);
            }
        });

        lauchLabel.setText("点击登录");

        javax.swing.GroupLayout lauchLayout = new javax.swing.GroupLayout(lauch);
        lauch.setLayout(lauchLayout);
        lauchLayout.setHorizontalGroup(
            lauchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lauchLayout.createSequentialGroup()
                .addComponent(lauchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lauchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 212, Short.MAX_VALUE))
        );
        lauchLayout.setVerticalGroup(
            lauchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lauchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lauchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lauchLabel))
        );

        settingButton.setText("jButton14");

        javax.swing.GroupLayout windowButtonLayout = new javax.swing.GroupLayout(windowButton);
        windowButton.setLayout(windowButtonLayout);
        windowButtonLayout.setHorizontalGroup(
            windowButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        windowButtonLayout.setVerticalGroup(
            windowButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        announcementShow.setViewportView(announcementText);

        announcementSendButton.setText("jButton11");

        announcementEditPanel.setViewportView(announcementEdit);

        javax.swing.GroupLayout announcementPanelLayout = new javax.swing.GroupLayout(announcementPanel);
        announcementPanel.setLayout(announcementPanelLayout);
        announcementPanelLayout.setHorizontalGroup(
            announcementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementPanelLayout.createSequentialGroup()
                .addGroup(announcementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(announcementEditPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                    .addComponent(announcementShow, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(announcementSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        announcementPanelLayout.setVerticalGroup(
            announcementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementPanelLayout.createSequentialGroup()
                .addComponent(announcementShow, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(announcementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(announcementEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(announcementSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton5.setText("答疑区");

        jButton6.setText("经验交流区");

        jButton7.setText("精品区");

        javax.swing.GroupLayout buttonAreaLayout = new javax.swing.GroupLayout(buttonArea);
        buttonArea.setLayout(buttonAreaLayout);
        buttonAreaLayout.setHorizontalGroup(
            buttonAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonAreaLayout.setVerticalGroup(
            buttonAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleMouseDragged(evt);
            }
        });
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                titleMouseReleased(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("文泉驿等宽微米黑", 3, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("学在工大");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(233, 233, 233))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        midArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        midArea.setDividerLocation(250);

        inputScrollPanel.setViewportView(inputTextPanel);

        jButton4.setText("jButton4");

        javax.swing.GroupLayout messageButtonPanelLayout = new javax.swing.GroupLayout(messageButtonPanel);
        messageButtonPanel.setLayout(messageButtonPanelLayout);
        messageButtonPanelLayout.setHorizontalGroup(
            messageButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        messageButtonPanelLayout.setVerticalGroup(
            messageButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageButtonPanelLayout.createSequentialGroup()
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        messageSendButton.setText("jButton8");

        exchangeButton.setText("<");
        exchangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeButtonActionPerformed(evt);
            }
        });

        showTextPanel.setEditable(false);
        showScrollPanel.setViewportView(showTextPanel);

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roomList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        roomScrollPanel.setViewportView(roomList);

        painterToolPanel.setOrientation(javax.swing.SwingConstants.VERTICAL);
        painterToolPanel.setRollover(true);

        jButton10.setText("jButton10");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        painterToolPanel.add(jButton10);

        javax.swing.GroupLayout centerAreaLayout = new javax.swing.GroupLayout(centerArea);
        centerArea.setLayout(centerAreaLayout);
        centerAreaLayout.setHorizontalGroup(
            centerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerAreaLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(centerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerAreaLayout.createSequentialGroup()
                        .addGroup(centerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centerAreaLayout.createSequentialGroup()
                                .addComponent(inputScrollPanel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(messageSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(centerAreaLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(messageButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(centerAreaLayout.createSequentialGroup()
                        .addComponent(showScrollPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exchangeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painterToolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        centerAreaLayout.setVerticalGroup(
            centerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerAreaLayout.createSequentialGroup()
                .addGroup(centerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showScrollPanel)
                    .addComponent(exchangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painterToolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerAreaLayout.createSequentialGroup()
                        .addComponent(messageButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(centerAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputScrollPanel)
                            .addGroup(centerAreaLayout.createSequentialGroup()
                                .addComponent(messageSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(roomScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
        );

        rightArea.addTab("tab1", centerArea);

        midArea.setRightComponent(rightArea);

        jButton3.setText("jButton3");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(jTextPane3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout leftAreaLayout = new javax.swing.GroupLayout(leftArea);
        leftArea.setLayout(leftAreaLayout);
        leftAreaLayout.setHorizontalGroup(
            leftAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftAreaLayout.setVerticalGroup(
            leftAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftAreaLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(leftAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(leftAreaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        midArea.setLeftComponent(leftArea);

        editMenu.setText("Edit");
        menuBar.add(editMenu);

        fileMenu.setText("File");
        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lauch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(midArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(buttonArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(announcementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(windowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lauch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(midArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(announcementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exchangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exchangeButtonActionPerformed

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        windowPoint .x = this.getX();
        windowPoint.y = this.getY();
    }//GEN-LAST:event_titleMousePressed

    private void titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseDragged
        windowPoint.x = evt.getX()+windowPoint.x;
        windowPoint.y = evt.getY()+windowPoint.y;
        this.setLocation(windowPoint.x, windowPoint.y);
    }//GEN-LAST:event_titleMouseDragged

    private void titleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_titleMouseReleased

    private void lauchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lauchMousePressed
        windowPoint .x = this.getX();
        windowPoint.y = this.getY();
    }//GEN-LAST:event_lauchMousePressed

    private void lauchMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lauchMouseDragged
        windowPoint.x = evt.getX()+windowPoint.x;
        windowPoint.y = evt.getY()+windowPoint.y;
        this.setLocation(windowPoint.x, windowPoint.y);
    }//GEN-LAST:event_lauchMouseDragged

    private void lauchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lauchButtonMouseClicked
       Dimension dim = Launcher.getPreferredSize();
       int fatherWidth = this.getWidth();
       int fatherHeight = this.getHeight();
        Launcher.setSize(dim);
        Launcher.setLocation( (fatherWidth-dim.width)/2, (fatherHeight-dim.height)/2);
        Launcher.setVisible(true);
    }//GEN-LAST:event_lauchButtonMouseClicked

    private void usernameInputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputerActionPerformed

    private void rememberUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberUserActionPerformed

    private void launchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_launchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Launcher;
    private javax.swing.JTextPane announcementEdit;
    private javax.swing.JScrollPane announcementEditPanel;
    private javax.swing.JPanel announcementPanel;
    private javax.swing.JButton announcementSendButton;
    private javax.swing.JScrollPane announcementShow;
    private javax.swing.JTextPane announcementText;
    private javax.swing.JCheckBox autoLaunch;
    private javax.swing.JPanel buttonArea;
    private javax.swing.JPanel centerArea;
    private javax.swing.JPanel drawPanel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton exchangeButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JScrollPane inputScrollPanel;
    private javax.swing.JTextPane inputTextPanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JPanel lauch;
    private javax.swing.JButton lauchButton;
    private javax.swing.JLabel lauchLabel;
    private javax.swing.JButton launchButton;
    private javax.swing.JPanel leftArea;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel messageButtonPanel;
    private javax.swing.JButton messageSendButton;
    private javax.swing.JSplitPane midArea;
    private javax.swing.JToolBar painterToolPanel;
    private javax.swing.JPasswordField passwordInputer;
    private javax.swing.JCheckBox rememberKey;
    private javax.swing.JCheckBox rememberUser;
    private javax.swing.JTabbedPane rightArea;
    private javax.swing.JList<String> roomList;
    private javax.swing.JScrollPane roomScrollPanel;
    private javax.swing.JButton settingButton;
    private javax.swing.JScrollPane showScrollPanel;
    private javax.swing.JTextPane showTextPanel;
    private javax.swing.JPanel title;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> usernameInputer;
    private javax.swing.JPanel windowButton;
    // End of variables declaration//GEN-END:variables

    private static Point windowPoint = new Point();

    /**
     * Get the value of windowPoint
     *
     * @return the value of windowPoint
     */
    /*public*/ static Point getWindowPoint() {
        return windowPoint;
    }

    /**
     * Set the value of windowPoint
     *
     * @param windowPoint new value of windowPoint
     */
    /*public*/ static void setWindowPoint(Point windowPoint) {
        Home.windowPoint = windowPoint;
    }
}
