/*
 * yinan.java
 *
 * Created on __DATE__, __TIME__
 */

package gui.form;

/**
 *
 * @author  __USER__
 */
public class fankui extends javax.swing.JInternalFrame {

	/** Creates new form yinan */
	public fankui() {
		initComponents();
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setClosable(true);
		setIconifiable(true);
		setResizable(true);
		setTitle("\u8ddf\u6211\u53cd\u9988");

		jLabel1.setText("\u641c\u7d22\u4e00\u4e0b\uff1a");

		jButton4.setText("\u641c\u7d22");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "1", "��ѧ", "4+4", "10" },
						{ "2", "��ѧ", "4+4", "10" }, { "3", "��ѧ", "4+4", "10" },
						{ "4", "��ѧ", "4+4", "10" } }, new String[] { "���",
						"��Ŀ", "����", "����" }));
		jScrollPane1.setViewportView(jTable1);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(298, 298, 298)
						.add(jLabel1)
						.add(57, 57, 57)
						.add(jTextField1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								242,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(41, 41, 41).add(jButton4)
						.addContainerGap(317, Short.MAX_VALUE))
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(jScrollPane1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								1060, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(116, 116, 116)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jButton4)
								.add(jLabel1)
								.add(jTextField1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.add(53, 53, 53)
						.add(jScrollPane1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								562, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}