/*
 * yinan.java
 *
 * Created on __DATE__, __TIME__
 */

package gui.form;

/**
 *
 * @author  __USER__
 */
public class jinghua extends javax.swing.JInternalFrame {

	/** Creates new form yinan */
	public jinghua() {
		initComponents();
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setClosable(true);
		setIconifiable(true);
		setResizable(true);
		setTitle("\u7cbe\u534e\u793e\u533a");

		jLabel1.setText("\u641c\u7d22\u4e00\u4e0b\uff1a");

		jButton4.setText("\u641c\u7d22");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "1", "��ѧ", "4+4", "10" },
						{ "2", "��ѧ", "4+4", "10" }, { "3", "��ѧ", "4+4", "10" },
						{ "4", "��ѧ", "4+4", "10" } }, new String[] { "���",
						"��Ŀ", "����", "����" }));
		jScrollPane1.setViewportView(jTable1);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jScrollPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1140,
						Short.MAX_VALUE)
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(423, Short.MAX_VALUE)
								.add(jLabel1)
								.add(57, 57, 57)
								.add(jTextField1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										235,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(48, 48, 48).add(jButton4)
								.add(260, 260, 260)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(195, Short.MAX_VALUE)
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jButton4)
										.add(jTextField1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												23,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel1))
								.add(105, 105, 105)
								.add(jScrollPane1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										459,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}