/*
 * yinan.java
 *
 * Created on __DATE__, __TIME__
 */

package gui.form;

/**
 *
 * @author  __USER__
 */
public class yinan extends javax.swing.JInternalFrame {

	/** Creates new form yinan */
	public yinan() {
		initComponents();
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u5f20\u4e09\u7684\u7591\u96be\u89e3\u7b54");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("\u5f55\u5236\u8bed\u97f3");

		jButton2.setText("\u5b9e\u65f6\u8bed\u97f3");

		jButton3.setText("\u53d1\u9001");

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jScrollPane3.setViewportView(jTextArea3);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(jScrollPane1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										871, Short.MAX_VALUE)
								.add(jScrollPane2,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										871, Short.MAX_VALUE)
								.add(org.jdesktop.layout.GroupLayout.TRAILING,
										layout.createSequentialGroup()
												.addContainerGap()
												.add(jButton1)
												.add(53, 53, 53)
												.add(jButton2)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED,
														576, Short.MAX_VALUE)
												.add(jButton3,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														68,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jScrollPane3,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								261,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(jScrollPane1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								411,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jButton1).add(jButton2).add(jButton3))
						.add(18, 18, 18)
						.add(jScrollPane2,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								330, Short.MAX_VALUE))
				.add(jScrollPane3,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 792,
						Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	// End of variables declaration//GEN-END:variables

}